### ISSUE TITLE
Not working for Atom 1.17.2

### ISSUE THREAD

**Issue by levity** [joekr/theme-toggler#8]
The option to toggle themes no longer shows up in the command palette.

**Comment by joekr** [comment]
Thank you for letting me know. I will try to look into this sometime next week.

**Comment by joekr** [comment]
I'm seeing it in the command palette in 1.18.0. Are you still on 1.17.2? Upgrading should help fix it. If that doesn't fix it let me know.

**Comment by levity** [comment]
Works for me in 1.18.0!
